Store in ~/.nix-home, as /var/run/user/1000 does not survive reboots or X restarts. Fixes #3

diff --git a/nix-home b/nix-home
--- a/nix-home
+++ b/nix-home
@@ -5,6 +5,9 @@ if [ ! -e $HOME/default.nix ]; then
 	exit -1
 fi
 
+mkdir -p $HOME/.nix-home
+ROOT=$HOME/.nix-home/current-home/
+
 function fail() {
 	echo "Failed to run"
 	rm $TMPFILE
@@ -13,9 +16,13 @@ function fail() {
 
 # enumerate over every file in current-home, store in TMPFILE
 TMPFILE=`mktemp`
+prefix=$ROOT
 if [ -e /var/run/user/$UID/current-home ]; then
 	find /var/run/user/$UID/current-home/ -type f > $TMPFILE
 	find /var/run/user/$UID/current-home/ -type l >> $TMPFILE
+elif [ -e $ROOT ]; then
+	find $ROOT -type f > $TMPFILE
+	find $ROOT -type l >> $TMPFILE
 fi
 
 # remove current home
@@ -23,11 +30,11 @@ fi
 #rm -f /var/run/user/$UID/current-home
 
 # replace current-home folder
-nix-build -I NIXHOME -o /var/run/user/$UID/current-home $HOME || fail
+echo "nix-build -I NIXHOME -o $ROOT $HOME || fail"
+nix-build -I NIXHOME -o $ROOT $HOME || fail
 
 # link all files in current home to $HOME
-prefix="/var/run/user/$UID/current-home/"
-for x in `find /var/run/user/$UID/current-home/ -type l`; do
+for x in `find $ROOT -type l`; do
 	dest=${x#$prefix}
 
 	if [ ! -h "$HOME/$dest" ]; then
@@ -45,7 +52,7 @@ for x in `find /var/run/user/$UID/current-home/ -type l`; do
 	fi
 done
 
-for x in `find /var/run/user/$UID/current-home/ -type f`; do
+for x in `find $ROOT -type f`; do
 	dest=${x#$prefix}
 	echo "linking $x to $dest"
 	ln -sf $x -t `dirname $HOME/$dest`
